@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

class Main {
}


package "config"{

 class SessionConfig {
     + {static} sessionConfig()
     }
 class ThymeleafConfig{
    + {static} templateEngine()
    }
}

package "controllers"{
'Done'
class AdminController {
+ {static} addRoutes()
+ {static} adminLogin()
+ {static} checkAdminLogin()
+ {static} updateOrder()
+ {static} updateOrderStatus()
+ {static} showUnprocessedOrders()
+ {static} showUnprocessedOrder()
+ {static} showPendingOrders()
+ {static} showPendingOrder()
+ {static} showProcessedOrders()
+ {static} showProcessedOrder()
+ {static} showOfferPage()
+ {static} showOfferPageConfirmation()
+ {static} showBomPage()
+ {static} sendOffer()
}
'Done'
class OrderController {
+ {static} addRoutes()
+ {static} getCarportSvg()
+ {static} handleCarportInfo()
+ {static} handleConfirmation()
+ {static} showConfirmationPage()
+ {static} saveOrderToDatabase()
+ {static} showPaymentPage()
+ {static} confirmPayment()
}
}

package "entities"{

class Admin{
- int adminId
- String username
- String password

+ getters and setters()

}

'Done'
class Component {
- int componentId
- int orderId
- int materialVariantId
- int quantity
- String useDescription
- MaterialVariant materialVariant

+ getters and setters()
}
'Done'
class Customer {
- int customerId
- String customerName
- String customerEmail
- String customerAddress
- int customerZipcode
- String customerPhone

+ getters and setters()
}

'Done'
class Material {
- int materialId
- String name
- String unit
- double price

+ getters and setters()
}
'Done'
class MaterialVariant {
- int materialVariantId;
- int materialId
- int length
- Material material

+ getters and setters()
}
'Done'
class Order {
- int orderId
- int customerId
- int carportWidth
- int carportLength
- String roof
- String customerText
- String adminText
- int statusId
- double salesPrice
- Timestamp createdAt
- Customer customer

+ getters and setters()
}

'Done'
class OrderStatus{
- int statusId
- String status

+ getters and setters()

}
'Done'
class Svg{
- int svgId
- int orderId
- String svgData
- Timestamp createdAt

+getters and setters()
}

'Done'

class Zipcode{
- int zipcode
- String city

+getters and setters()
}

package "exceptions"{
     class DatabaseException {
     + DatabaseException ()
     + DatabaseException ()
     + DatabaseException ()
      }
}


package "mapper"{
'Done'
package "admin" {
class AdminLoginMapper {
+ {static} boolean checkAdminLoginCredentials()

}
'Skal evt. slettes helt?'
class AdminMapper{

}

package "component"{

class ComponentMapper{
+ {static} saveOrderComponentsToDB()
}

package "customer"{

class CustomerMapper{
+ {static} Customer saveSessionCustomer()
+ {static} String getCustomerEmailById()
}

package "material"{
'Skal evt. slettes helt?'
class MaterialMapper{
}

class MaterialVariantMapper{
+ {static} List<MaterialVariant> getMaterialVariantsByIdAndMinLength
}

package "order"{

class OrderMapper{
+ {static} Order saveSessionOrder()
+ {static} updateOrderForSeller()
+ {static} updateOrderStatus()
+ {static} Order getOrderById()
+ {static} Order getUnprocessedOrderById()
+ {static} List<Order> getOrderSummariesByStatus()
+ {static} List<Component> getAllComponentsByOrderId()

}
'Skal evt. slettes helt?'
class OrderStatusMapper{

}

package "svg"{
'Skal evt. slettes helt?'
class SvgMapper{
}

package "persistence"{

 class ConnectionPool {
- {static} volatile ConnectionPool instance
- {static} HikariDataSource ds
- {static} final Logger LOGGER

- ConnectionPool()

+ {static} getInstance()
+ getConnection()
+ close()
+ {static} createHikariConnectionPool()
}
}


package "service"{

package "admin"{

class AdminLoginService{
+ {static} String handleAdminLogin()
}
'Skal evt. slettes helt?'
class AdminService{
}


package "component" {
class ComponentService {
+ {static} saveOrderComponentsToDB()
+ {static} List<Component> calculateBom()

}
}
}

}
'Skal evt. slettes helt'?
package "material" {
class MaterialVariantService {
}

class MaterialService {
}

}

package "order" {
class CarportCalculatorService{
}
class CarportSvg{

}


class OrderService {

}

class OrderStatusService{


}

class Svg{

}

package "svg" {
class CarportSvg {
}

class Svg {
}
}

package "user" {
class UserService {
}
}

}

Main -- "controllers"
Main -- "config"

"mapper" -- "entities": Laver Entities objekter


'Entitet relationer




@enduml

implements ..|>
extends <|-- (is-a)
composition *-- (must-have)
Aggregation o-- (can-have)
Associering <--
