@startuml
'https://plantuml.com/sequence-diagram
!pragma layout smetana

class Main {
}


package "config"{

 class SessionConfig {
     + {static} sessionConfig()
     }
 class ThymeleafConfig{
    + {static} templateEngine()
    }
}

package "controllers"{
'Done'
class AdminController {
+ {static} addRoutes(Javalin app, ConnectionPool connectionPool)
+ {static} adminLogin(Context ctx, ConnectionPool connectionPool)
+ {static} checkAdminLogin(Context ctx)
+ {static} updateOrder(Context ctx, ConnectionPool connectionPool)
+ {static} updateOrderStatus(Context ctx, ConnectionPool connectionPool)
+ {static} showUnprocessedOrders(Context ctx, ConnectionPool connectionPool)
+ {static} showUnprocessedOrder(Context ctx, ConnectionPool connectionPool)
+ {static} showPendingOrders(Context ctx, ConnectionPool connectionPool)
+ {static} showPendingOrder(Context ctx, ConnectionPool connectionPool)
+ {static} showProcessedOrders(Context ctx, ConnectionPool connectionPool)
+ {static} showProcessedOrder(Context ctx, ConnectionPool connectionPool)
+ {static} showOfferPage(Context ctx, ConnectionPool connectionPool)
+ {static} showOfferPageConfirmation(Context ctx, ConnectionPool connectionPool)
+ {static} showBomPage(Context ctx, ConnectionPool connectionPool)
+ {static} sendOffer(Context ctx, ConnectionPool connectionPool)
}
'Done'
class OrderController {
+ {static} addRoutes(Javalin app, ConnectionPool connectionPool)
+ {static} getCarportSvg(Context ctx)
+ {static} handleCarportInfo(Context ctx)
+ {static} handleConfirmation(Context ctx, ConnectionPool connectionPool)
+ {static} showConfirmationPage(Context ctx)
+ {static} saveOrderToDatabase(Context ctx, ConnectionPool connectionPool)
+ {static} showPaymentPage(Context ctx, ConnectionPool connectionPool)
+ {static} confirmPayment(Context ctx, ConnectionPool connectionPool)
}
}


package "entities"{

class Admin{
- int adminId
- String username
- String password

+ getters and setters()

}

'Done'
class Component {
- int componentId
- int orderId
- int materialVariantId
- int quantity
- String useDescription
- MaterialVariant materialVariant

+ getters and setters()
}
'Done'
class Customer {
- int customerId
- String customerName
- String customerEmail
- String customerAddress
- int customerZipcode
- String customerPhone

+ getters and setters()
}

'Done'
class Material {
- int materialId
- String name
- String unit
- double price

+ getters and setters()
}
'Done'
class MaterialVariant {
- int materialVariantId;
- int materialId
- int length
- Material material

+ getters and setters()
}
'Done'
class Order {
- int orderId
- int customerId
- int carportWidth
- int carportLength
- String roof
- String customerText
- String adminText
- int statusId
- double salesPrice
- Timestamp createdAt
- Customer customer

+ getters and setters()
}

'Done'
class OrderStatus{
- int statusId
- String status

+ getters and setters()

}
'Done'
class Svg{
- int svgId
- int orderId
- String svgData
- Timestamp createdAt

+getters and setters()
}

'Done'

class Zipcode{
- int zipcode
- String city

+getters and setters()
}
}

package "exceptions"{
     class DatabaseException {
     + DatabaseException (String userMessage)
     + DatabaseException (String userMessage, String systemMessage)
     + DatabaseException (String userMessage, Throwable cause)
      }
}


package "mapper"{
'Done'
package "admin" {
class AdminLoginMapper {
+ {static} boolean checkAdminLoginCredentials(String username, String password, ConnectionPool connectionPool)

}
'Skal evt. slettes helt?'
class AdminMapper{

}

package "component"{

class ComponentMapper{
+ {static} saveOrderComponentsToDB(List<Component> orderComponents, ConnectionPool connectionPool)
}

package "customer"{

class CustomerMapper{
+ {static} Customer saveSessionCustomer(Customer customer, ConnectionPool connectionPool)
+ {static} String getCustomerEmailById(int customerId, ConnectionPool connectionPool)
}

package "material"{
'Skal evt. slettes helt?'
class MaterialMapper{
}

class MaterialVariantMapper{
+ {static} List<MaterialVariant> getMaterialVariantsByIdAndMinLength(int materialId, int minLength, ConnectionPool connectionPool)
}


package "order"{

class OrderMapper{
+ {static} Order saveSessionOrder(Order order, ConnectionPool connectionPool)
+ {static} updateOrderForSeller(Order order, ConnectionPool connectionPool)
+ {static} updateOrderStatus(int orderId, int statusId, ConnectionPool connectionPool)
+ {static} Order getOrderById(int orderId, ConnectionPool connectionPool)
+ {static} Order getUnprocessedOrderById(int orderId, ConnectionPool connectionPool)
+ {static} List<Order> getOrderSummariesByStatus(int statusId, ConnectionPool connectionPool)
+ {static} Order getOrderAndCustomerInfoByOrderId(int orderId, ConnectionPool connectionPool)
+ {static} List<Component> getAllComponentsByOrderId(int orderId, ConnectionPool connectionPool)

}
'Skal evt. slettes helt?'
class OrderStatusMapper{

}

package "svg"{
'Skal evt. slettes helt?'
class SvgMapper{
}


package "persistence"{

 class ConnectionPool {
- {static} volatile ConnectionPool instance
- {static} HikariDataSource ds
- {static} final Logger LOGGER

- ConnectionPool()

+ {static} getInstance(String user, String password, String url, String db)
+ getConnection()
+ close()
+ {static} createHikariConnectionPool(String user, String password, String url, String db)
}
}


package "service"{

package "admin"{

class AdminLoginService{
+ {static} String handleAdminLogin(String username, String password, Context ctx, ConnectionPool connectionPool)
}
'Skal evt. slettes helt?'
class AdminService{
}


package "component" {
class ComponentService {
+ {static} saveOrderComponentsToDB(List<Component> orderComponents, ConnectionPool connectionPool)
+ {static} List<Component> calculateBom(Order order, ConnectionPool connectionPool)

}
package "customer" {

class CustomerService{

+ {static} Customer saveSessionCustomer(String name, String email, String address, int zipCode, String phone, ConnectionPool connectionPool)
+ {static} getCustomerEmailById(int customerId, ConnectionPool connectionPool)
}
}
package "email"{

class EmailService{

+ {static} sendOfferEmail(Order order, String customerEmail)
+ {static} String buildOfferContent(Order order)
}
}

}
'Skal evt. slettes helt'?
package "material" {
class MaterialVariantService {
}

class MaterialService {
}

}

package "order" {
class CarportCalculatorService{

-ArrayList<Component> orderComponents
-int width
-int length
-ConnectionPool connectionPool

+ List<Component> calculateCarportBOM(Order order)
+ double calculateCarportMaterialCost(List<Component> orderComponents)
+ calculatePosts(Order order)
+ int calculatePostQuantity()
+ calculateBeams(Order order)
+ int calculateBeamsJoiningPoint()
+ calculateRafters(Order order)
+ int calculateRaftersQuantity(int length)

}
class CarportSvg{
- Svg svgDrawing
- int width
- int length
'Mangler resten af attributterne her'

+ addBeams()
+ addRafters()
+ addPost()
+ addText()
+ String toString()
}


class OrderService {

+ {static} createOrderAndCustomer(String name, String email, String address, int zipCode, String phone,
   int width, int length, String roof, String customerText, ConnectionPool connectionPool)
+ {static} Order saveSessionOrder(int customerId, int width, int length, String roof, String userText, ConnectionPool connectionPool)
+ {static} updateOrderForSeller(int orderId, int width, int length, String roof, String customerText, String adminText, double salesPrice, int statusId, ConnectionPool connectionPool)
+ {static} updateOrderStatus(int orderId, int statusId, ConnectionPool connectionPool)
+ {static} Order getOrderById(int orderId, ConnectionPool connectionPool)
+ {static} List<Order> getOrderSummariesByStatus(int statusId, ConnectionPool connectionPool)
+ {static} Order getUnprocessedOrderById(int orderId, ConnectionPool connectionPool)
+ {static} updateOrderAndSendOffer(int orderId, int width, int length, String roof, String customerText, String adminText, double salesPrice, int statusId, ConnectionPool connectionPool)
+ {static} getOrderAndCustomerInfoByOrderId(int orderId, ConnectionPool connectionPool)
+ {static} double calculateEstimatedSalesPrice(double coverageRate, double carportTotalPrice)
+ {static} Order validateAndFetchOrder(String orderIdParam, ConnectionPool connectionPool)


}
'Skal evt. slettes helt?'
class OrderStatusService{

}

class Svg{
- StringBuilder svg

+ addRectangle(double x, double y, double width, double height, String style)
+ addLine(int x1, int y1, int x2, int y2, String style)
+ addText(int x, int y, int rotation, String text, int fontSize)
+ addMarker()
+ String toString()

}
}

Main -- "controllers"
Main -- "config"

"mapper" -- "entities": Laver Entities objekter


'Entitetsrelationer'
Customer o-- Order
Order *-- Customer
MaterialVariant *-- Material
Customer *-- Zipcode
Component *-- MaterialVariant
Order *-- OrderStatus

Customer "1" --> "0..*" Order
MaterialVariant "1" --> "1" Material
Customer "1" --> "1" Zipcode
Component "1" --> "1" MaterialVariant
Order "1" --> "0..*" Component
Order "1" --> "1" OrderStatus
Order "1" --> "1" Svg









@enduml
1:1 → "1" --> "1"

1:mange → "1" --> "0..*"

mange:1 → "* " --> "1"

evt. 0 → "0..1" eller "0..*"


implements ..|>
extends <|-- (is-a)
composition *-- (must-have)
Aggregation o-- (can-have)
Associering <--
