@startuml
!pragma layout smetana

object User{
+role
}
object Order{
+orderStatus
}
object Component
object MaterialVariant{
+length
}
object Material
object Svg
object Sug

User *-- Order
Order *-- Component
Order o-- Svg
Order o-- Sug

Component *-- MaterialVariant
MaterialVariant *-- Material

@enduml
