@startuml
skinparam monochrome true
skinparam shadowing false
left to right direction
title Kunde Flow – Fog Bestillingssystem
@startuml

start

:Kunde åbner frontPage.html;

:Udfylder formular 1 (navn, adresse, tlf, e-mail);
:POST /formular1;
:CustomerController.handleFormular1();

:Udfylder formular 2 (vælger materialer + SVG tegning);
:POST /formular2;
:CustomerController.handleFormular2();

:OrderMapper.insertOrder();
:MaterialVariantMapper.insertVariant();
:BillOfMaterialsMapper.insertBom();

:Ordre gemt i database;
stop
@enduml
hej
